server:
  port: 8085

spring:
  application:
    name: api-gateway
#  cloud:
#    gateway:
#      routes:
#        - id: event-api-route
#          uri: http://event-api:8090
#          predicates:
#            - Path=/event-api/**
#          filters:
#            - StripPrefix=1

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always

logging:
  level:
    org.springframework.cloud.gateway: TRACE
    org.springframework.http.server.reactive: DEBUG